# Generated by Django 6.0.2 on 2026-07-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
