# Generated by Django 6.0.2 on 2026-04-09 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_user'),
        ('tenants', '0002_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property'),
        ),
    ]
