# Generated by Django 6.0.2 on 2026-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents/id_cards/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kra_pin',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents/kra_pins/'),
        ),
    ]
