# Generated by Django 6.0.2 on 2026-07-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_id_card_front_back_kra_pin_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='id_card_front',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
