# Generated by Django 6.0.2 on 2026-07-20 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_tenant_id_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
