# Generated by Django 6.0.2 on 2026-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_receipts/'),
        ),
    ]
