# Generated by Django 6.0.2 on 2026-07-20 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
